spring.datasource.url=jdbc:postgresql://localhost:5433/blueprints
spring.datasource.username=blueprints
spring.datasource.password=blueprints
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
